Data_Preparation:
  test_size: 0.20
  random_state: 40

Train:
  Random_Forest:
    n_estimators: 479
    criterion: 'squared_error'
    max_depth: 21
    max_features: 1
    min_samples_split: 10
    min_samples_leaf: 5
    max_samples: 0.67
    verbose: 1
    n_jobs: -1

  LightGBM:
    n_estimators: 160
    max_depth: 30
    learning_rate: 0.27
    subsample: 0.7592213724048168
    min_child_weight: 20
    min_split_gain: 0.004604680609280751
    reg_lambda: 97.81002379097947
    n_jobs: -1